version: "3.9"
services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - .postgres:/var/lib/postgres/data

  web:
    build: .
    command:  uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql://habrpguser:pgpwd4habr@postgres:5432/habrdb"
    depends_on:
      - postgres
